### ISSUE TITLE
Starting capl_filt on Windows

### ISSUE THREAD

**Issue by albert-github** [BretislavRychta/CAPL-filter-for-Doxygen#1]
The, minimal, description is for Linux and similar systems. For Windows there is a small change required.

`INPUT_FILTER           = capl_filter.pl`

works OK for Linux due to the possibility to automatically start the perl file. On windows we need:

`INPUT_FILTER           = "perl <path_to>/capl_filter.pl"`

**Comment by BretislavRychta** [comment]
It depends how well/bad you have installed the Perl. I'm using Windows and it works.
